/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 03-ago-2020 4:50:54 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS cajero CASCADE
;

DROP TABLE IF EXISTS CajeroOperacion CASCADE
;

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Tarjeta CASCADE
;

DROP TABLE IF EXISTS Transaccion CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE cajero
(
	idCajero varchar(50) NOT NULL,
	fechaCaje varchar(50) NOT NULL,
	saldoCaje varchar(50) NOT NULL
)
;

CREATE TABLE CajeroOperacion
(
	ids varchar(50) NOT NULL,
	idCajero varchar(50) NULL,
	idTrans integer NULL
)
;

CREATE TABLE Cuenta
(
	numCue integer NOT NULL,
	estadoCue boolean NOT NULL,
	saldoCue integer NOT NULL,
	fechaAper date NULL,
	Cedula integer NULL,
	NumeroTar integer NULL
)
;

CREATE TABLE Tarjeta
(
	NumeroTar integer NOT NULL,
	claveTar integer NOT NULL,
	fechaVen date NOT NULL,
	estadoTar boolean NOT NULL,
	numCue integer NULL
)
;

CREATE TABLE Transaccion
(
	idTrans integer NOT NULL,
	numCue integer NULL,
	ids varchar(50) NULL,
	nombreTrans varchar(50) NULL
)
;

CREATE TABLE Usuario
(
	Cedula integer NOT NULL,
	nombreUsu varchar(100) NOT NULL,
	apellidoUsu varchar(100) NOT NULL,
	telefonoUsu integer NOT NULL,
	direccionUsu varchar(50) NOT NULL,
	numCue integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cajero ADD CONSTRAINT PK_Cuenta
	PRIMARY KEY (idCajero)
;

ALTER TABLE CajeroOperacion ADD CONSTRAINT PK_CajeroOperacion
	PRIMARY KEY (ids)
;

CREATE INDEX IXFK_CajeroOperacion_cajero ON CajeroOperacion (idCajero ASC)
;

CREATE INDEX IXFK_CajeroOperacion_Transaccion ON CajeroOperacion (idTrans ASC)
;

ALTER TABLE Cuenta ADD CONSTRAINT PK_Cajero
	PRIMARY KEY (numCue)
;

CREATE INDEX IXFK_Cuenta_Tarjeta ON Cuenta (NumeroTar ASC)
;

CREATE INDEX IXFK_Cuenta_Usuario ON Cuenta (Cedula ASC)
;

ALTER TABLE Tarjeta ADD CONSTRAINT PK_Tarjeta
	PRIMARY KEY (NumeroTar)
;

ALTER TABLE Transaccion ADD CONSTRAINT PK_Transaccion
	PRIMARY KEY (idTrans)
;

CREATE INDEX IXFK_Transaccion_Cuenta ON Transaccion (numCue ASC)
;

ALTER TABLE Usuario ADD CONSTRAINT PK_Usuario
	PRIMARY KEY (Cedula)
;

/* Create Foreign Key Constraints */

ALTER TABLE CajeroOperacion ADD CONSTRAINT FK_CajeroOperacion_cajero
	FOREIGN KEY (idCajero) REFERENCES cajero (idCajero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE CajeroOperacion ADD CONSTRAINT FK_CajeroOperacion_Transaccion
	FOREIGN KEY (idTrans) REFERENCES Transaccion (idTrans) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Tarjeta
	FOREIGN KEY (NumeroTar) REFERENCES Tarjeta (NumeroTar) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Usuario
	FOREIGN KEY (Cedula) REFERENCES Usuario (Cedula) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Transaccion ADD CONSTRAINT FK_Transaccion_Cuenta
	FOREIGN KEY (numCue) REFERENCES Cuenta (numCue) ON DELETE No Action ON UPDATE No Action
;
